let BDgatos = [
    {
        nombre: "Matilde  ",
        raza: "British Shorthair",
        edad: "6 Meses",
        ubicacion: "4140 Parker Rd. Allentown, New Mexico 31134",
        personalidad: ["Juguetón", "Tierno", "Inquieto"],
        historia: "Matilde es la mejor guarda espaldas, siempre esta ahi para conversar y recibirte cada día con un gran cariño. Fue rescatada y busca una persona que le pueda dar todo el amor que ella necesita.",
        usuario : "Junior López",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/4g8GDH8/gato1.jpg",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id: 0,
        categoria: "gato"
    },
    {
        nombre: "Kity",
        raza: "Bombay",
        edad: "9 meses",
        ubicacion: "Calle 12-15aa - 103 - Santa Fé, Bogotá",
        personalidad: ["Inquieto", "Juguetón", "Curioso"],
        historia: "Kitty es un torbellino en todo su esplendor suele ser muy juguetona, muy inquieta y sobre todo suele ser muy cariñosa, al principio puede costar acostumbrarse a sus constantes juegos pero con el tiempo te darás cuenta que es una excelente compañera. La razón por la cual me tengo que alejar de Kitty es debido que mis padres se van a mudar conmigo y mi madre es alérgica a los gatos, espero encontrar una familia que la adopte y que le dé mucho amor.",
        usuario : "Junior López",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/rKBf4Z4/gato2.jpg",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id: 1,
        categoria: "gato"
    },
    {
        nombre: "Pelusa ",
        raza: "Birmano",
        edad: "11 meses",
        ubicacion: "Calle 53-12c - 113 - Santa Fé, Bogotá",
        personalidad: ["Curioso", "Cariñoso", "Paciente"],
        historia: "Pelusa es un gato muy muy curioso, le encanta los días lluviosos y suele ser muy paciente con los niños, es un gato muy hogareño, le encanta dormir y no suele hacer daños en el hogar. La razón por la cual tenemos que dejar ir a pelusa es porque me salió una propuesta de trabajo en el exterior y tengo que viajar en poco tiempo, así que estoy buscando una persona que lo sepa cuidar y que le dé todo lo que necesite.",
        usuario : "Junior López",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/HB5nHCb/gato3.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id : 2,
        categoria: "gato"
    },
    {
        nombre: "Bombón",
        raza: "Gato americano ",
        edad: "10 meses",
        ubicacion: "Calle 74-53b - 93 - Santa Fé, Bogotá",
        personalidad: ["Perezoso", "Tranquilo", "Cariñoso"],
        historia: "Le pusimos bombón debido a que desde que era muy pequeña le encantaba dormir en su camita así que cada vez que se acostaba parecía una bolita y eso dice mucho de ella, no es una gata muy activa ,suele dormir la mayor parte del día, y le encanta la compañía por las tardes. La razón por la cual tengo que dejar ir a bombón es porque trabajó jornadas muy extensas y no me está quedando tiempo para cuidarla así que busco alguien que le pueda dar todo lo que ella merece.",
        usuario : "Junior López",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/rZWphyC/gato4.jpg",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id : 3,
        categoria: "gato"
    },
    {
        nombre: "Tito",
        raza: "Ragdoll",
        edad: "3 meses",
        ubicacion: "Calle 38-110a 190 - Santa Fé, Bogotá",
        personalidad: ["Aventurero", "Juguetón", "Tierno"],
        historia : "Tito es un gato, miembro de una gran camada que nació hace poco y está esperando un hogar donde le den mucho amor, ya está preparado totalmente para adopción y tener mucha felicidad en su vida. Es gracioso y no se separa de su peluche.",
        usuario: "Junior López",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/c6Hf6HW/Gato-Ragdoll-1.png",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id : 4,
        categoria: "gato"
    },
    {
        nombre: "Patricia",
        raza: "Munchkin",
        edad: "1 año",
        ubicacion: "Calle 80-450a 580 - Santa Fé, Bogotá",
        personalidad: ["Cariñoso", "Juguetón", "Curioso"],
        historia : "Patricia es una gato, encontrado en la calle con quemaduras en su piel por el sol fue rescatado y está totalmente recuperado y listo para adoptar.",
        usuario: "Junior López",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/v4KQR0k/M.png",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id : 5,
        categoria: "gato"
    },
    {
        nombre: "Minino",
        raza: "Esfinge",
        edad: "6 meses",
        ubicacion: "Calle 17-120f 140 - Santa Fé, Bogotá",
        personalidad: ["Inquieto", "Juguetón", "Curioso"],
        historia : "Tortilla es una gata bebé que va a ser muy grande cuando esté en su total crecimiento, iba a ser vendida y además era maltratada, fue rescatada y ahora espera un hogar con mucho amor, le encanta tomar leche y jugar con otros gatitos.",
        usuario: "Junior López",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/x84rdFL/c7a39b5ae8bc74417b6a47fa66298d33.png",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id : 6,
        categoria: "gato"
    },
    {
        nombre: "Cosnia",
        raza: "Siames",
        edad: "2 años",
        ubicacion: "Calle 45-120b 138 - Santa Fé, Bogotá",
        personalidad: ["Cariñoso", "Tranquilo", "Perezoso"],
        historia : "Bosnia fue recogida de la calle, la usaban para criar hijos y la dejaban de nuevo en la calle, espera un hogar donde por fin la acepten y le den mucho amor, es tranquila y algo perezosa.",
        usuario: "Junior López",
        imgusuario : "https://i.ibb.co/hR5BMh8/Jr.png",
        imagen: "https://i.ibb.co/gDFRRCp/gato8.jpg",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id : 7,
        categoria: "gato"
    },
    {
        nombre: "Marshmello",
        raza: "Himalayo",
        edad: "4 años",
        ubicacion: "Calle 45-120b 138 - Santa Fé, Bogotá",
        personalidad: ["Cariñoso", "Tranquilo", "Perezoso"],
        historia : "Marshmello es un gato amoroso y seguro de sí mismo que está listo para cualquier aventura. Le encanta jugar con otros gatos y le encantaría unirse a una casa que ya tiene un gato para poder tener otros amigos con quienes jugar. Es muy activo y necesita una casa con un jardín y una familia que pueda satisfacer sus necesidades.",
        usuario: "Junior López",
        imgusuario : "https://i.ibb.co/hR5BMh8/Jr.png",
        imagen: "https://i.ibb.co/938xpLv/Gato-himalayo.png",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id : 8,
        categoria: "gato"
    },
    {
        nombre: "Logan",
        raza: "Tonkinés",
        edad: "2 años",
        ubicacion: "Calle 45-120b 138 - Santa Fé, Bogotá",
        personalidad: ["Cariñoso", "Tranquilo", "Perezoso"],
        historia : "Super dulce y juguetona. Logan será una gran adición a cualquier hogar.",
        usuario: "Junior López",
        imgusuario : "https://i.ibb.co/hR5BMh8/Jr.png",
        imagen: "https://i.ibb.co/z7PQPc6/GATO-TONKIN-S.png",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id : 9,
        categoria: "gato"
    }
]

export default BDgatos