let BDperros = [
    {
        nombre: "Chester",
        raza: "Golden retriever",
        edad: "12 meses",
        ubicacion: "Calle 54-12b 108 - Santa Fé, Bogotá",
        personalidad: ["Aventurero", "Paciente", "Tranquilo"],
        historia: "Chester es un perro muy valiente y leal, por lo general suele ser muy tranquilo, casi ni se siente en la casa, además es muy cariñoso y obediente . La razón por la cual nos tenemos que separar de él es porque nos vamos a ir a vivir al exterior y él desafortunadamente no nos puede acompañar, entonces estamos en busca de una persona que lo sepa cuidar con todo el corazón.",
        usuario: "Junior  López",
        imgusuario: "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/nsxG80m/perro2.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 0,
        categoria: "perro"
    },
    {
        nombre: "Rocky",
        raza: "Rottweiler",
        edad: "3 meses",
        ubicacion: "4140 Parker Rd. Allentown, New Mexico 31134",
        personalidad: ["Cariñoso", "Juguetón", "Inquieto"],
        historia: "Rocky es un perrito muy lindo y cariñoso, tiene 5 hermanitos más y por cuestiones de espacio y tiempo no podremos cuidar a todos, nuestra misión es encontrar la familia ideal para él y seguro que tú eres la persona indicada.",
        usuario: "Junior López",
        imgusuario: "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/WDfQyqB/perro1.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 1,
        categoria: "perro"
    },
    {
        nombre: "Papi",
        raza: "Chihuahua",
        edad: "5 meses",
        ubicacion: "Calle 32-120b 180 - Santa Fé, Bogotá",
        personalidad: ["Cariñoso", "Juguetón", "Aventurero"],
        historia: "Papi es un perrito que llegó a nuestras vidas gracias a que lo encontramos en una casa abandonada, es un perro que es muy protector con sus dueños y que siempre está de buen humor. La razón por la que no lo puedo tener más es porque mi novio es alérgico a los perro asi que estamos buscando una familia que le de mucho amor.",
        usuario: "Junior López",
        imgusuario: "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/tHgRQZh/perro3.jpg",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 2,
        categoria: "perro"
    },
    {
        nombre: "Pelusa",
        raza: "Bichón frisé",
        edad: "8 meses",
        ubicacion: "Calle 23-42a 113 -Santa Fé, Bogotá",
        personalidad: ["Tranquilo", "Cariñoso", "Curioso"],
        historia: "Pelusa es una perrita que fue previamente entrenado en una academia canina así que suele ser muy obediente y tranquila, ella llego a mi vida ya que fue un regalo de un amigo pero lastimosamente dónde me voy a mudar no me permiten tener mascotas así que estoy buscando a una familia que la cuide y le de mucho amor.",
        usuario: "Junior López.",
        imgusuario: "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/tpxYdr8/perro4.jpg",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id: 3,
        categoria: "perro"
    },
    {
        nombre: "Zafiro",
        raza: "Matín Italiano",
        edad: "2 meses",
        ubicacion: "Calle 12-160b 130 - Santa Fé, Bogotá",
        personalidad: ["Cariñoso", "Tranquilo", "Paciente"],
        historia: "Rufi es una cachorro de una camada de 6 perritos que se encontraron en la calle con su madre en estado de desnutrición. Está un poco enfermito pero siempre está alegre y cariñoso, buscamos a la mejor familia que pueda darle los cuidados que necesita.",
        usuario: "Junior López",
        imgusuario: "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/cC4RvPd/Mastin-italiano.png",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 4,
        categoria: "perro"
    },
    {
        nombre: "Nolberto",
        raza: "Dachshund",
        edad: "1 año",
        ubicacion: "Calle 62-420b 18 - Santa Fé, Bogotá",
        personalidad: ["Aventurero", "Cariñoso", "Inquieto"],
        historia: "Santo fue rescatado de las peleas callejeras, traído a recuperación debido a sus múltiples heridas por otros perros y sus antiguos amos, ahora es un perro muy protector en buscar de un nuevo hogar lleno amor.",
        usuario: "Junior López",
        imgusuario: "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/hXkvD29/daschund.png",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id: 5,
        categoria: "perro"
    },
    {
        nombre: "Jesus Enrique",
        raza: "Pitbull Terrier",
        edad: "1 año",
        ubicacion: "Calle 22-320c 10 - Santa Fé, Bogotá",
        personalidad: ["Perezoso", "Tranquilo", "Curioso"],
        historia: "Jesús Enrique fue traído por sus antiguos dueños, ellos no la podian cuidar luego de que se volvió mamá, llegó con sus 3 cachorros y estamos buscando una familia que pueda adoptarlos a todos, no queremos separarlos.",
        usuario: "Junior López",
        imgusuario: "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/K0gdq2s/Pitbull.png",
        genero: "https://i.ibb.co/QbnsP1H/Property-1-female.png",
        id: 6,
        categoria: "perro"
    },
    {
        nombre: "Ripout",
        raza: "Beagle",
        edad: "6 meses",
        ubicacion: "calle 32-132d 110 - Santa Fé, Bogotá",
        personalidad: ["Aventurero", "Curioso", "Inquieto"],
        historia : "Su amor es infinito puro e incondicional, el es un eterno cachorro que solo piensa en amarnos.Es pequeño ágil y te morderá los tobillos.",
        usuario: "Junior López.",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/GRR5M32/img-beagle.png",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id : 7,
        categoria: "perro"
    },
    {
        nombre: "Laurent",
        raza: "Pastor Alemán",
        edad: "3 años",
        ubicacion: "calle 32-132d 110 - Santa Fé, Bogotá",
        personalidad: ["Aventurero", "Curioso", "Inquieto"],
        historia : "Laurent Vivía entre basura y apenas tenía fuerzas para comer a causa de todas las enfermedades que padecía. Mostraba temor a los humanos pero en seguida confió en el servicio de rescate de PetsApp. Dónde Laurent recibió todo el cariño que se merece.",
        usuario: "Junior López.",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/bK9gybn/Img.png",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id : 8,
        categoria: "perro"
    },
    {
        nombre: "Beethoven",
        raza: "San Bernardo",
        edad: "4 años",
        ubicacion: "calle 32-132d 110 - Santa Fé, Bogotá",
        personalidad: ["Aventurero", "Curioso", "Inquieto"],
        historia : "Beethoven es un canino súper dulce que busca un hogar. Le encanta caminar, hacer senderismo y nadar. Le va muy bien con otros perros y gatos. No ama a los niños, pero podría acostumbrarse a ellos si se le exponen lo suficiente.",
        usuario: "Junior López.",
        imgusuario : "https://i.ibb.co/8M069vD/Jrjesus.png",
        imagen: "https://i.ibb.co/xzftQmB/img-san-Bernardo.png",
        genero: "https://i.ibb.co/xFWqvbb/Component-5.png",
        id : 9,
        categoria: "perro"
    }
]

export default BDperros